[project]
name = "sentiment-analysis"
version = "0.1.0"
description = "Machine Learning in Finance Final Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
